spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://database-1.ckvujnqnmnxb.ap-northeast-2.rds.amazonaws.com:3306/dev-apartment-price?serverTimezone=Asia/Seoul
        username: dev
        password: asdfqwer
